### ISSUE TITLE
Slow running speed

### ISSUE THREAD

**Issue by paulomann** [MSeal/cython_hunspell#12]
Hello, 

I'm using your API for some tests, and it seems to me that the running speed is slow. Also, checking in the System Monitor, it seems to be using 100% of one CPU core. Is that the case? Or maybe I'm doing something wrong.... I'm also using two dictionaries to check against at the same time.

**Comment by MSeal** [comment]
I'm assuming you're running `suggest` operations? Yes they're slow, but that's the Hunspell library. The CyHunspell wrapper doesn't add any substantial overhead. The calls will eat a whole core while processing. This is why the wrapper bakes in caching and bulk functions to allow for parallelism and fast repeated queries.

**Comment by paulomann** [comment]
Sorry that I did not make myself clear. Yes, I am using `suggest` operations.

I see, so there is nothing that we could do to improve it, right?

**Comment by MSeal** [comment]
I spent a lot of time making sure the code was as optimal as possible. Suggestion searching is a computationally expensive operation, you'll have a hard time doing exactly what it's doing more efficiently. If you have repeated suggestion requests you make a lot across executions you can add `disk_cache_dir` to persist the API cache, which makes the commonly repeated API calls extremely fast. If you can define a more specialized operation, or greedy outcome, you may be able to come up with an algorithm that's less computationally expensive to find words in a local state space. In the past I did some work where we mapped word spaces into vector spaces to find "suggestions" with a higher error rate at a much higher efficiency. There's a whole field of NLP processing branches that can be applied. But Hunspell is a specific tool in that space and `suggest` will always have a similar performance profile to now.

**Comment by paulomann** [comment]
Hmmm. I understand. Thanks for your attention and clarification!
