### ISSUE TITLE
Import fails on MacOS 10.14

### ISSUE THREAD

**Issue by amitness** [MSeal/cython_hunspell#14]
The library installs successfully. I also have already installed hunspell with `brew install hunspell`. But, when importing the library,
```
import hunspell
```

It throws an error similar to this. `pyhunspell` replaced with `cyhunspell`
![image](https://user-images.githubusercontent.com/8587189/66922181-47884280-f046-11e9-9c55-931745279b67.png)

**Comment by MSeal** [comment]
Hmm what version of hunspell is brew providing you?

And what does `pkg-config --libs --cflags hunspell` give you?

**Comment by amitness** [comment]
@MSeal Looks like this was a device-specific issue. Closing it.
