### ISSUE TITLE
Need MSVC++ 14 error

### ISSUE THREAD

**Issue by prabhatM** [MSeal/cython_hunspell#15]
![cyhunspell_error_1](https://user-images.githubusercontent.com/7250780/68067784-4e1af780-fd72-11e9-8c61-58d1a78917b4.png)
![cyhunspell_error_2](https://user-images.githubusercontent.com/7250780/68067785-4eb38e00-fd72-11e9-8205-f23b59b30055.png)

Hi,

I had installed CyHunspell on my Windows 7.0 before, tested and worked with Python 3.6.

After 8-9 months, when I wanted to make a modification with a fresh installation, it refused to work and kept asking for MSVC++14 again and again.  I couldn't figure out the reason.

After investigation, I realised I had changed to Python 3.7 and the latest MSVC++ (2015-2019) was loaded, perhaps due to the latest Visual Studio Code.

I uninstalled and installed MSVC++2015 and Python 3.6.5 but CyHunspell refuses to install on my Windows 7, SP1, 64bit machine.

Please advise.

Note :  It works fine on Ubuntu 18.4

Regards

Prabhat

**Comment by MSeal** [comment]
I think to solve this permanently I'll need to create a pre-compiled wheel for windows builds. I'm unlikely to be able to get to it for a month or two though :/.

**Comment by prabhatM** [comment]
Thank you for your reply. That's very
encouraging.

Regards

Prabhat MOHANTY

**Comment by MSeal** [comment]
Long time since this was reported. But the new 2.0.0 release should resolve this issue now with wheel support added
