### ISSUE TITLE
Add not working

### ISSUE THREAD

**Issue by mttcnnff** [MSeal/cython_hunspell#18]
I saw that `add` was recently added but it doesn't seem to be working, wondering if I'm doing something wrong....

![image](https://user-images.githubusercontent.com/17532157/69272343-7e50fb80-0ba4-11ea-9464-1ac148402c56.png)

**Comment by MSeal** [comment]
I haven't snapped of a release with the change. I can do that this weekend. In the meantime you need to install from the master branch to pick up the change.

**Comment by MSeal** [comment]
Version 1.3.3 is released with the add functionality
