### ISSUE TITLE
Upgrade Windows and OS X to Hunspell 1.7.x

### ISSUE THREAD

**Issue by MSeal** [MSeal/cython_hunspell#2]
Trying to perform this upgrade for OS X resulting in many seg faults -- root cause was not clear after some debugging.
Windows would need new visual studio builds against the new version created.

**Comment by zdenop** [comment]
There is already version [1.7.0](https://github.com/hunspell/hunspell/releases)

**Comment by MSeal** [comment]
Thanks. I updated the description. Mostly I've been swamped by different open source project code bases demands so haven't been able to dedicate a long weekend to moving this to wheels / updating to latest hunspell base.

**Comment by MSeal** [comment]
2.0.0 release moved to 1.7.0 :tada:
