### ISSUE TITLE
[Feature request]: add rest of hunspell library functions 

### ISSUE THREAD

**Issue by zdenop** [MSeal/cython_hunspell#20]
As far as I understand cython_hunspell support only part of [library functions](https://github.com/hunspell/hunspell/releases/download/v1.7.0/hunspell3.pdf).

Is it possible to include rest of functions (namely add_dic, add_with_affix, analyze, generate, remove, get_dic_encoding...)?

**Comment by MSeal** [comment]
I think that'd be reasonable to add in combination with a bump to the new version of the hunspell.

**Comment by MSeal** [comment]
This should now be done with the 2.0.0 release -- except for `generate` for which the C++ calls don't seem to follow documentation for results so I skipped it.
