### ISSUE TITLE
pip install Cyhunspell

### ISSUE THREAD

**Issue by dhanusht97** [MSeal/cython_hunspell#23]
pip install CyHunspell doesn't work on windows and but it have worked on kaggle when I have installed , but it doesn't work on windows

**Comment by MSeal** [comment]
@dhanusht97 Try now -- there's a new 2.0.0 release that just went out that improves installation (python 3.6-3.8 only though).

**Comment by dhanusht97** [comment]
Thanks @MSeal for your immediate response ,it's working now
