### ISSUE TITLE
Horrible error trying to pip install in Python 3.9 env

### ISSUE THREAD

**Issue by jeanmonet** [MSeal/cython_hunspell#29]
I not yet certain if the problem is related to my machine's config or related to the fact that I'm trying to install on a Python 3.9 environment, but trying to pip install inside a Python 3.9 environment (Ubuntu 20 machine) gives the following (very long) error output:

https://pastebin.com/JBSLRWY2

**Comment by MSeal** [comment]
Thanks for reporting. I need to get 3.9 builds working in general as the 2.x releases don't have a 3.9 wheel yet and pip was trying to build the old 1.x release patterns from the egg. I'll try to find some time in the near future to do this update.

**Comment by jeanmonet** [comment]
Got it. Many thanks for your work on this library.

**Comment by MSeal** [comment]
Was working on this over the weekend some -- oxs builds for 3.9 were causing issues. I think I got it sorted but I'm going to let the next build run to see (takes an 45+min between runs to confirm builds across OS options)

**Comment by MSeal** [comment]
@jeanmonet 3.9 support is released with 2.0.2 on PyPI now. I tried to sneak 3.10 support in there but the alpha builds aren't fully ready for CI tooling yet.

**Comment by jeanmonet** [comment]
Awesome! Thanks a lot for your work on this lib.
