### ISSUE TITLE
"Unable to locate package" on Ubuntu 16.04

### ISSUE THREAD

**Issue by nmatthews-asapp** [MSeal/cython_hunspell#3]
When following the instructions to install hunspell 1.6 I get the following error message:
```
$ sudo apt-get install libhunspell-1.6-0 libhunspell-dev
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package libhunspell-1.6-0
E: Couldn't find any package by glob 'libhunspell-1.6-0'
E: Couldn't find any package by regex 'libhunspell-1.6-0'
```

**Comment by MSeal** [comment]
Sorry for missing this thread back when it was made.

I added more clear instructions with https://github.com/MSeal/cython_hunspell/commit/1b5168eed0bcd562df8333dc55447b2aa57c202a
but the library works with both 1.6 and 1.3 so for older ubuntu versions you can install 1.3 safely. Normally if you can't install dependencies the `pip install cyhunspell` it downloads the dependency for you.
