### ISSUE TITLE
No install instructions; Install fails

### ISSUE THREAD

**Issue by nmatthews-asapp** [MSeal/cython_hunspell#4]
I don't see any install instructions on the README;

https://github.com/chrisjbryant/lmgec-lite
suggests using `pip install -U CyHunspell`

When I do so, I get:
```
RuntimeError: Package hunspell was not found in the pkg-config search path.
    Perhaps you should add the directory containing `hunspell.pc'
    to the PKG_CONFIG_PATH environment variable
    No package 'hunspell' found
```

The instructions indicate hunspell will automatically be installed and setup so this shouldn't happen. To troubleshoot I tried running the command provided but it didn't work. See https://github.com/MSeal/cython_hunspell/issues/3

Finally I tried simply `sudo apt-get install hunspell` which worked fine but this setup is still broken.
I will continue to troubleshoot and try setting this environment variable, but ideally the README would provide enough instruction to start using the library.

**Comment by Shirlly** [comment]
Hi @nmatthews-asapp, I met the same problem. Have you find the directory containing "hunspell.pc" or did you make it for the installation and setup?

**Comment by MSeal** [comment]
Sorry I missed this thread at the time.

What OS and python version where you using? It should default to downloading libhunspell if it can't find a system installation. We have tests for python 2.7 and 3.6/3.7 for a few linux distros and osx running on travis which are passing so I'd like to narrow down what version combinations isn't working by default.

**Comment by LuisVilarBarbosa** [comment]
Hi,
I would like to indicate that I've tried performing "pip install cyhunspell" on Windows 10, MX Linux (Debian-based) and Docker and both MX Linux and Docker give the error mentioned above. Windows 10 works fine. I've tested versions 1.3.3 and 1.3.4. On MX Linux, only libhunspell-1.7-0 is available, so it might be part of the problem.

**Comment by LuisVilarBarbosa** [comment]
Improving the last comment, on Windows 10, the installation works without problems, on MX Linux, it is necessary to explicitly install libhunspell-dev for the installation to complete successfully, and, on Docker, it is necessary to explicitly install g++ and libhunspell-dev.

**Comment by dhanusht97** [comment]
ERROR: Command errored out with exit status 1:
     command: 'C:\ProgramData\Anaconda3\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\dhanu\\AppData\\Local\\Temp\\pip-install-jk9lx7vc\\CyHunspell\\setup.py'"'"'; __file__='"'"'C:\\Users\\dhanu\\AppData\\Local\\Temp\\pip-install-jk9lx7vc\\CyHunspell\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\dhanu\AppData\Local\Temp\pip-install-jk9lx7vc\CyHunspell\pip-egg-info'
         cwd: C:\Users\dhanu\AppData\Local\Temp\pip-install-jk9lx7vc\CyHunspell\
    Complete output (22 lines):
    Downloading http://downloads.sourceforge.net/hunspell/hunspell-1.3.3.tar.gz to C:\Users\dhanu\AppData\Local\Temp\pip-install-jk9lx7vc\CyHunspell\external\hunspell-1.3.3.tar.gz
    Extracting C:\Users\dhanu\AppData\Local\Temp\pip-install-jk9lx7vc\CyHunspell\external\hunspell-1.3.3.tar.gz to C:\Users\dhanu\AppData\Local\Temp\pip-install-jk9lx7vc\CyHunspell\external
    Traceback (most recent call last):
      File "C:\Users\dhanu\AppData\Local\Temp\pip-install-jk9lx7vc\CyHunspell\find_library.py", line 226, in pkgconfig
        raise RuntimeError(response)
    RuntimeError: Unable to create process using 'c:\users\dhanu\appdata\local\programs\python\python38-32\python.exe "C:\Users\dhanu\AppData\Local\Programs\Python\Python38-32\Scripts\pykg-config.py"  --libs --cflags hunspell'

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\dhanu\AppData\Local\Temp\pip-install-jk9lx7vc\CyHunspell\setup.py", line 46, in <module>
        hunspell_config = pkgconfig('hunspell', language='c++')
      File "C:\Users\dhanu\AppData\Local\Temp\pip-install-jk9lx7vc\CyHunspell\find_library.py", line 251, in pkgconfig
        os.path.join(BASE_DIR, 'external'))
      File "C:\Users\dhanu\AppData\Local\Temp\pip-install-jk9lx7vc\CyHunspell\tar_download.py", line 51, in download_and_extract
        extract_contents(file_name_from_url(url, directory), directory)
      File "C:\Users\dhanu\AppData\Local\Temp\pip-install-jk9lx7vc\CyHunspell\tar_download.py", line 42, in extract_contents
        tar = tarfile.open(file_name)
      File "C:\ProgramData\Anaconda3\lib\tarfile.py", line 1578, in open
        raise ReadError("file could not be opened successfully")
    tarfile.ReadError: file could not be opened successfully
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.




THis is the Error I am facing while installing CyHunspell

**Comment by MSeal** [comment]
This issue should be removed with 2.0.0 release

**Comment by dhanusht97** [comment]
Thanks @MSeal  it's working

**Comment by OscarWang114** [comment]
@LuisVilarBarbosa Thanks for the comment! I was able to fix the same issue by installing libhunspell-dev. For reference, I'm using Debian 9 and python 3.6.11 installed by anaconda.

**Comment by MSeal** [comment]
When I get 2.0 released for conda specifically you won't need that libhunspell-dev dependency, but that's a separate issue. You can also get 2.0 by adding cython_hunspell as a pip dependency to you conda environment I believe.
