### ISSUE TITLE
If I typed `inc`, any way to get all words starting with  `inc` in a dictionary ?

### ISSUE THREAD

**Issue by redstoneleo** [MSeal/cython_hunspell#6]
1. If I typed `inc`, any way to get all words starting with  `inc` in a dictionary ?
2. Any way to get all words in a dictionary ?

**Comment by MSeal** [comment]
Not directly. Hunspell doesn't support that type of operator out of the box. But you can read the dic and aff files directly to extract the words into a set in python, though asking questions of this set will be slower than direct Hunspell calls.

This code will populate the `words` variable with all words in the current lang dictionary (defaults to en_US). There are many other dictionaries, such as seen in https://github.com/wooorm/dictionaries, you might use.

```
import os
from hunspell import Hunspell
h = Hunspell()

dic = os.path.join(h._hunspell_dir, h.lang + '.dic')
aff = os.path.join(h._hunspell_dir, h.lang + '.aff')

encoding = 'utf-8'
with open(aff, 'r') as aff: 
     for line in aff.readlines(): 
         if line.startswith('SET '): 
             encoding = line.split(' ')[-1].strip() 
             break

with open(dic, 'rb') as dfile: 
     words = {row.decode(encoding).split('/', 1)[0].strip() for row in dfile.readlines()}
```

**Comment by redstoneleo** [comment]
Thanks for your help ! But I encountered the following exception when run the code.

```
Traceback (most recent call last):
  File "D:\hsdict.py", line 10, in <module>
    for line in aff.readlines():
UnicodeDecodeError: 'gbk' codec can't decode byte 0xc9 in position 6178: illegal multibyte sequence
```

**Comment by MSeal** [comment]
Hmm, your add file must have an odd encoding I'm not aware of. Maybe try to open as binary and decode once you find the right line?

```
with open(aff, 'rb') as aff:  
      for line in aff.readlines():  
          if line.startswith(b'SET '):  
              encoding = line.decode().split(' ')[-1].strip()  
              break 
```

**Comment by redstoneleo** [comment]
Great ! Thanks very much !
I found [the aff file](https://github.com/MSeal/cython_hunspell/blob/master/dictionaries/en_US.aff ) is encoded with `ISO8859-1`
